version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vue3-base
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - '8080:8080'
    volumes:
      - '.:/usr/src/app'
      - /usr/src/app/node_modules
    restart: always
